version: 1.0.{build}

branches:
    only:
        - master

clone_folder: c:\projects\emscripten-opengl

image:
    - Visual Studio 2019
    - Visual Studio 2017

clone_script:
    - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

configuration:
    - Debug
    - Release

platform:
    - x64
    - x86

environment:
    matrix:
        - arch: Win64

init:
    - set arch=
    - if "%arch%"=="Win64" ( set arch= Win64)
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 16 2019%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
    - echo %generator%

build_script:
    - mkdir build
    - cd build
    - cmake --version
    - cmake -DENABLE_TESTS=ON .. -G %generator%

test_script:
    ctest -C %CONFIGURATION% -VV