version: 1.0.{build}

branches:
    only:
    - master

clone_folder: c:\projects\emscripten-opengl

clone_script:
    - ps: >-
        if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
          cd $env:APPVEYOR_BUILD_FOLDER
          git checkout -qf $env:APPVEYOR_REPO_COMMIT
        } else {
          git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
          cd $env:APPVEYOR_BUILD_FOLDER
          git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
          git checkout -qf FETCH_HEAD
        }
    - cmd: git submodule update --init --recursive

image:
- Visual Studio 2019
- Visual Studio 2017

configuration:
- Debug
- Release

platform:
- x64

environment:
    matrix:
    - arch: Win64

init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake -DENABLE_TESTS=ON .. -G %generator%

build:
    project: c:\projects\emscripten-opengl\build\Emscripten_Graphics.sln
    verbosity: minimal
    parallel: true