version: 1.0.{build}

branches:
    only:
        - master

clone_folder: c:\projects\emscripten-opengl

image:
    - Visual Studio 2019
    - Visual Studio 2017

clone_script:
    - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

configuration:
    - Debug

platform:
    - x64
    - x86

environment:
    matrix:
        - arch: Win64

build_script:
    - mkdir build
    - cd build
    - cmake --version
    - cmake -DENABLE_TESTS=ON ..
    - cmake --build .

test_script:
    ctest -C %CONFIGURATION% -VV