version: 1.0.{build}

branches:
    only:
    - master

clone_folder: c:\projects\emscripten-opengl

image:
- Visual Studio 2017
- Visual Studio 2019

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

configuration:
- Debug
- Release

platform:
- x64

environment:
    matrix:
    - arch: Win64


before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake -DENABLE_TESTS=ON ..

build:
    project: c:\projects\emscripten-opengl\build\Emscripten_Graphics.sln
    verbosity: minimal
    parallel: true