version: '3.6'

services:
    application:
        build: .
        volumes: 
            - ./application/out:/app/build/application/out
        command: sh execapp.sh
        ports: 
            - "8080:8080"
    resbuild:
        build: .
        command: sh execbuild.sh