application:
    window:
        width: 1280
        height: 720
        title: "test"
        resizable: on
    shaders:
        filename: ""
        with_light: on
    models:
        list: []
        startup: ""
        settings:
            x_rotation: []
            y_rotation: []
            z_rotation: []
            scaling: []
            translation: []
    texture: 
    lights:
        directional: []
        point: []
    camera:
        position: []
        direction: []
        world_up: []
    common:
        MSAA: on
        sensitivity: 0.15
        speed: 6.0
        line_mode: off